# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 690f5aff8830e2ce8218a9ee0ab736648fa8e78ee3a75ca98267df67b724818823afdee028f5617cfd2c86365c58c5de66a9242b3899aaedf2b8213488b06b72

test:
  secret_key_base: 52f242be94c951c5237aa390e6a7a7ace3e020215944a4ce35220dd3206fc4409a4e118bb64551ff42dfb9e5f1be20c01450df9326c88895307e495f1afa6d5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
